{
 "title": "INMET Data Processing Dashboard",
 "time": { "from": "2014-01-01T00:00:00.000Z", "to": "2023-12-01T00:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "states",
    "label": "Estados",
    "query": "select distinct co_df from state_per_year_month"
   },
   {
    "name": "regions",
    "label": "Regiões",
    "query": "select distinct co_regiao from region_per_year_month"
   }
  ]
 },
 "panels": [
  { "title": "Estações", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperatura por Estações",
   "type": "geomap",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "select avg(nu_latitude) as nu_latitude, avg(nu_longitude) as nu_longitude, co_estacao, max(ds_estacao) as ds_estacao, avg(nu_temperatura_avg_celcius) as nu_temperatura_avg_celcius from estacao_per_year_month where $__timeFilter(year_month) group by   co_estacao"
    },
    {
     "rawSql": "select avg(nu_latitude) as nu_latitude, avg(nu_longitude) as nu_longitude, co_estacao, max(ds_estacao) as ds_estacao, avg(nu_precipitacao_total_avg_milimetro) as nu_precipitacao_total_avg_milimetro from estacao_per_year_month where $__timeFilter(year_month) group by   co_estacao"
    }
   ]
  },
  {
   "title": "Top 10 Maiores temperaturas",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "select co_estacao, max(ds_estacao) as ds_estacao, max(nu_temperatura_max_celcius) as nu_temperatura_max_celcius from estacao_per_year_month where $__timeFilter(year_month) and nu_temperatura_avg_celcius is not null group by co_estacao order by max(nu_temperatura_max_celcius) desc limit 10;"
    }
   ]
  },
  {
   "title": "Top 10 Menores temperaturas",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "select co_estacao, max(ds_estacao) as ds_estacao, min(nu_temperatura_min_celcius) as nu_temperatura_min_celcius from estacao_per_year_month where $__timeFilter(year_month) and nu_temperatura_min_celcius is not null group by co_estacao order by min(nu_temperatura_min_celcius) asc limit 10;"
    }
   ]
  },
  { "title": "Regiões", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Média de temperatura por Região [$regions]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "repeat": "regions",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "select co_regiao, year_month, nu_temperatura_max_celcius, nu_temperatura_avg_celcius, nu_temperatura_min_celcius from region_per_year_month  where co_regiao = $regions "
    }
   ]
  },
  {
   "title": "Precipitação por região [$regions]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "repeat": "regions",
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "rawSql": "select co_regiao, year_month, nu_precipitacao_total_avg_milimetro from region_per_year_month  where co_regiao = $regions "
    }
   ]
  },
  { "title": "Estados", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Temperatura por Estado [$states]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "repeat": "states",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "select co_df, year_month, nu_temperatura_max_celcius, nu_temperatura_avg_celcius, nu_temperatura_min_celcius from state_per_year_month where co_df = $states order by year_month desc "
    }
   ]
  },
  {
   "title": "Precipitação por Estado [$states]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "repeat": "states",
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "rawSql": "select co_df, year_month, nu_precipitacao_total_avg_milimetro from state_per_year_month where co_df = $states order by year_month desc "
    }
   ]
  }
 ]
}